---
title: "Dublin Midlands WaW Viewer"
format: 
  dashboard:
    theme:
      light: 
        - sketchy
        - custom.scss
    logo: images/clock.svg
    self-contained: true
editor_options: 
  chunk_output_type: inline
---

```{r}
library(plotly)
library(DT)
source("getData.R")
```


# Outpatients

## Column - Graph WaW {height = "60%"}

```{r}
#| title: Outpaitent's Weighted Average Wait Time Since 2022

plot_ly(Hospital_WaW, 
        x = ~report_date, 
        y = ~WaW, 
        color = ~`hospital name`, 
        type = 'scatter', 
        mode = 'lines+markers',
        hovertemplate = paste(
          "%{y}"
        ),
        customdata = ~`hospital name` # Include hospital name as custom data
) %>% 
  layout(
    hovermode = "x unified",  # Unified hover mode
    xaxis = list(title = "Week Ending", showgrid = FALSE),
    yaxis = list(title = "Weighted Average Wait Time", griddash = 'dot') # Transparent paper
  )


```

## Column - WaW Tables {height="30%"}

### Row - Hospital & Specialty WaW Tables {width="35%"} {.tabset}
```{r}
#| title: Current WaW by Hospital

# Create the table
current_hospital_WaW %>% 
  select(-report_date) %>% 
  rename(Hospital = `hospital name`) %>% 
datatable(
          options = list(
            paging = FALSE,       # Disable paging
            searching = FALSE,    # Disable search box
            columnDefs = list(
              list(targets = 0, width = '200px'),  # Adjust width of hospital name column
              list(targets = 1, width = '100px')   # Adjust width of WaW column
            )
          )
            ,rownames = FALSE)

```

```{r}
#| title: Current WaW by Speaciality

# Create the table
current_speciality_WaW %>% 
  select(-report_date) %>% 
datatable(
          options = list(
            paging = FALSE,       # Disable paging
            searching = FALSE,    # Disable search box
            columnDefs = list(
              list(targets = 0, width = '200px'),  # Adjust width of hospital name column
              list(targets = 1, width = '100px')   # Adjust width of WaW column
            )
          )
            ,rownames = FALSE)
```


### Row - Hospital Speciality Table {width="65%"}

```{r}
#| title: Current WaW by Hospital, Specialty

pivot_data <- Spec_Hos_WaW %>%
  pivot_wider(names_from = Specialty, values_from = WaW) %>% 
  rename(Hospital = `hospital name`)

datatable(
  pivot_data,
  extensions = 'Buttons', # Enable Buttons extension
  options = list(
    dom = 'Bfrtip', # Add buttons to the top of the table
    buttons = c('excel', 'print'), # Available buttons
    paging = FALSE,
    searching = FALSE
  ),
  rownames = FALSE
)

```

# Inpatients/Day Cases

```{r}
cat("Currently Under Construction: Coming Soon")
```


# GI Scopes

```{r}
cat("Currently Under Construction: Coming Soon")
```


